"use client";

import Link from "next/link";

export const metadata = {
  title: "Portfolio Home Page",
  description: "Generated by create next app description",
};

export default function Home() {
  return (
    <div className="flex flex-col justify-between items-center ">
      <div className="flex items-center font-bold text-[40px] text-text-color-black-100 w-[450px] sm:text-[50px] md:text-[60px] sm:w-[560px] md:w-[700px] text-center">  Living life Fully Stacked—One Solution</div>
      <p className="text-[20px] font-medium text-text-color-black-200 flex items-center justify-center mt-4 mb-10 space-x-2">
        <label>I’m Guy</label>
        <label className="text-text-color-green">Full-Stack</label>
        <label>Developer</label>
      </p>
      <div className="flex gap-10 justify-around">
        <Link href="/contact"className="font-medium text-[18px] py-3 px-8 bg-text-color-green shadow-lg hover:scale-110 transition-transform duration-200 ease-in-out text-text-color-white" >Contact </Link>
        <Link href="/about" className="font-medium text-[18px] py-3 px-8 bg-text-color-white shadow-lg hover:scale-110 transition-transform duration-200 ease-in-out text-text-color-black" > About </Link>
      </div>
    </div>
    
    

    
  );
}
